apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: usdf-butler2-backup
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: usdf-butler2
