
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: sdf-dmz
  labels:
    cnpg.io/cluster: dp03
  name: gcp-access-lb
  namespace: dp03
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: dp03
    role: primary
  sessionAffinity: None
  type: LoadBalancer
