
apiVersion: v1
kind: Service
metadata:
  labels:
    cnpg.io/cluster: dp03-replica
  name: dp03-replica-lb
  namespace: dp03-replica
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: dp03-replica
    role: primary
  sessionAffinity: None
  type: LoadBalancer
